apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/deployment.yml
- backend/service.yml
- backend/hpa.yml
- frontend/deployment.yml
- frontend/service.yml

images:
- name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/devops-na-nuvem-week/production/backend
  newName: 968225077300.dkr.ecr.us-east-1.amazonaws.com/devops-na-nuvem-week/production/backend
  newTag: 802770432c37c27a833334018302d8f0e693fd3d
- name: 968225077300.dkr.ecr.us-east-1.amazonaws.com/devops-na-nuvem-week/production/frontend
  newName: 968225077300.dkr.ecr.us-east-1.amazonaws.com/devops-na-nuvem-week/production/frontend
  newTag: 802770432c37c27a833334018302d8f0e693fd3d
